aws_region = "ap-south-1"
aws_name = "SIT Machine"
aws_ami = "ami-08df646e18b182346"
aws_instance = "t2.micro"
env_bucket  = "terraform-state-for-us-again"
environment_key = "sit-terraform-state/terraform.tfstate"
